### ISSUE TITLE
Contributing file for explaining how to work with me

### ISSUE THREAD

**Issue by skooi** [skooi/my-recipes#2]
Currently, the repository doesn't have good instructions for how a collaborator can contribute to this project. These people are typically outsiders
## TODO
- [x] `CONTRIBUTINT.md` created
- [x] Explain Fork and Pull Request Model
- [x] Link to it from `README.md`
